# Modified OneDark

# Default colors
[colors.primary]
background = "#1e222a"
foreground = "#abb2bf"

# Normal colors
[colors.normal]
black   = "#353b45"
red     = "#be5046"
green   = "#98c379"
yellow  = "#d19a66"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#b6bdca"

# Bright colors
[colors.bright]
black   = "#3e4451"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#c8ccd4" 
