#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V
bspc monitor DP-1 -d VI VII VIII IX X

# automation for multiple monitors. comment above 2 lines before uncommenting this.
#if [[ $(xrandr -q | grep "DP-1 connected") ]];
#   then
#      xrandr --output DP-1  --primary --mode 1920x1080 --pos 0x0  --rotate normal \
#             --output DVI-I-1 --off \
#             --output DVI-I-2 --off 
#      bspc monitor DP-1 -d I II III IV V VI VII VIII IX
#   fi

bspc config border_width         2
bspc config window_gap           8

bspc config normal_border_color "#484848"
bspc config focused_border_color "#ABE9B3"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
#bspc rule -a firefox state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# variables, makes the spaghetti look modular
#wallpaper="/home/rinojames007/MyFiles/script/pywall.jpg"
wmname LG3D

#xcompmgr &
#transset-df 0.9 &
udiskie &
#feh --no-fehbg --bg-scale  wallpaper
feh --no-fehbg --bg-scale "$HOME/Pictures/clouds-3.jpg"
#picom --experimental-backend --config ~/.config/picom/picom.conf
#$HOME/.scripts/battery.sh &
picom --config '/home/rinojames007/.config/picom/picom.conf' &
polybar &
